[package]
name = "ddddocr_ort"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.18", features = ["derive"] }
image = "0.25.2"
ndarray = "0.16.1"
ndarray-stats = "0.6.0"
ort = { version = "2.0.0-rc.6" }
serde_json = "1.0.128"
